### ISSUE TITLE
Console filled with errors

### ISSUE THREAD

**Issue by Ibotmealot** [YouHaveTrouble/PreventStabby#10]
```diff
- [Mon 14:56:46 ERROR Minecraft] Could not pass event EntityTargetLivingEntityEvent to PreventStabby v1.5
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because the return value of "org.bukkit.event.entity.EntityTargetEvent.getTarget()" is null
	at PreventStabby-1.5.jar//me.youhavetrouble.preventstabby.listeners.pets.PetTargettingPlayerListener.onPetTargetPlayer(PetTargettingPlayerListener.java:27)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:665)
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:279)
	at net.minecraft.world.entity.animal.Wolf.setTarget(Wolf.java:256)
	at net.minecraft.world.entity.animal.Wolf.mobInteract(Wolf.java:516)
	at net.minecraft.world.entity.Mob.interact(Mob.java:1300)
	at net.minecraft.world.entity.player.Player.interactOn(Player.java:1138)
	at net.minecraft.server.network.ServerGamePacketListenerImpl$6.performInteraction(ServerGamePacketListenerImpl.java:2592)
	at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2611)
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131)
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2551)
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67)
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.```

**Comment by YouHaveTrouble** [comment]
Huh, that's a weird one, seems like getTarget() from target event is returning null. Which doesn't make much sense, because target event fires when entity targets something.
Do you perhaps have any plugins that may set entity target?

**Comment by YouHaveTrouble** [comment]
Try latest release, should be fixed
