### ISSUE TITLE
nullpointer getLocation() in worlguardhook

### ISSUE THREAD

**Issue by xknat** [YouHaveTrouble/PreventStabby#9]
we are using geyser + floodgate

```
[08:50:13 ERROR]: Could not pass event EntityTargetLivingEntityEvent to PreventStabby v1.4
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getLocation()" because "player" is null
        at me.youhavetrouble.preventstabby.hooks.WorldGuardHook.isPlayerForcedToPvp(WorldGuardHook.java:57) ~[PreventStabby-1.4.jar:?]
        at me.youhavetrouble.preventstabby.players.PlayerManager.canDamage(PlayerManager.java:122) ~[PreventStabby-1.4.jar:?]
        at me.youhavetrouble.preventstabby.listeners.pets.PetTargettingPlayerListener.onPetTargetPlayer(PetTargettingPlayerListener.java:29) ~[PreventStabby-1.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-60]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityTargetLivingEvent(CraftEventFactory.java:1326) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.world.entity.ai.goal.TemptGoal.canUse(TemptGoal.java:53) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.canUse(WrappedGoal.java:22) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:129) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:863) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3288) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:630) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:62) ~[?:?]
        at net.minecraft.world.entity.animal.horse.AbstractHorse.aiStep(AbstractHorse.java:559) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2938) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:398) ~[?:?]
        at net.minecraft.world.entity.animal.horse.AbstractHorse.tick(AbstractHorse.java:597) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1149) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:675) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:653) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1457) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by YouHaveTrouble** [comment]
I think I see what's going on. Gonna take a look when I'm home from work

**Comment by YouHaveTrouble** [comment]
Try latest release, should be fixed
